[package]
name = "lamport-signature-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.0"
rand_chacha = "0.9.0-alpha.0"

num-bigint = "0.4.4"
num-traits = "0.2.18"

tiny-keccak = { version = "2.0", features = ["keccak"] }
blake3 = "1.5.4"
